spring:
    profiles:
        active: dev
    datasource:
        platform: postgresql
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${db_host}:${db_port}/${db_name}?currentSchema=public
        hikari:
            jdbc-url: jdbc:postgresql://${db_host}:${db_port}/${db_name}?currentSchema=public
